In [0]:
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
df_blog = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/blogtext.csv")

In [0]:
df_blog.shape

(681284, 7)

In [0]:
df_blog.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 681284 entries, 0 to 681283
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   id      681284 non-null  int64 
 1   gender  681284 non-null  object
 2   age     681284 non-null  int64 
 3   topic   681284 non-null  object
 4   sign    681284 non-null  object
 5   date    681284 non-null  object
 6   text    681284 non-null  object
dtypes: int64(2), object(5)
memory usage: 36.4+ MB


In [0]:
df_blog.head(10)

id  ...                                               text
0  2059027  ...             Info has been found (+/- 100 pages,...
1  2059027  ...             These are the team members:   Drewe...
2  2059027  ...             In het kader van kernfusie op aarde...
3  2059027  ...                   testing!!!  testing!!!          
4  3581210  ...               Thanks to Yahoo!'s Toolbar I can ...
5  3581210  ...               I had an interesting conversation...
6  3581210  ...               Somehow Coca-Cola has a way of su...
7  3581210  ...               If anything, Korea is a country o...
8  3581210  ...               Take a read of this news article ...
9  3581210  ...               I surf the English news sites a l...

[10 rows x 7 columns]

In [0]:
df_blog['topic'].unique()

array(['Student', 'InvestmentBanking', 'indUnk', 'Non-Profit', 'Banking',
       'Education', 'Engineering', 'Science', 'Communications-Media',
       'BusinessServices', 'Sports-Recreation', 'Arts', 'Internet',
       'Museums-Libraries', 'Accounting', 'Technology', 'Law',
       'Consulting', 'Automotive', 'Religion', 'Fashion', 'Publishing',
       'Marketing', 'LawEnforcement-Security', 'HumanResources',
       'Telecommunications', 'Military', 'Government', 'Transportation',
       'Architecture', 'Advertising', 'Agriculture', 'Biotech',
       'RealEstate', 'Manufacturing', 'Construction', 'Chemicals',
       'Maritime', 'Tourism', 'Environment'], dtype=object)

In [0]:
df_blog['sign'].unique()

array(['Leo', 'Aquarius', 'Aries', 'Capricorn', 'Gemini', 'Cancer',
       'Sagittarius', 'Scorpio', 'Libra', 'Virgo', 'Taurus', 'Pisces'],
      dtype=object)

In [0]:
df_blog['age'].unique()

array([15, 33, 14, 25, 17, 23, 37, 26, 24, 27, 45, 34, 41, 44, 16, 39, 35,
       36, 46, 42, 13, 38, 43, 40, 47, 48])

In [0]:
df_blog.groupby(df_blog['age']).count()

id  gender  topic   sign   date   text
age                                           
13   13133   13133  13133  13133  13133  13133
14   27400   27400  27400  27400  27400  27400
15   41767   41767  41767  41767  41767  41767
16   72708   72708  72708  72708  72708  72708
17   80859   80859  80859  80859  80859  80859
23   72889   72889  72889  72889  72889  72889
24   80071   80071  80071  80071  80071  80071
25   67051   67051  67051  67051  67051  67051
26   55312   55312  55312  55312  55312  55312
27   46124   46124  46124  46124  46124  46124
33   17584   17584  17584  17584  17584  17584
34   21347   21347  21347  21347  21347  21347
35   17462   17462  17462  17462  17462  17462
36   14229   14229  14229  14229  14229  14229
37    9317    9317   9317   9317   9317   9317
38    7545    7545   7545   7545   7545   7545
39    5556    5556   5556   5556   5556   5556
40    5016    5016   5016   5016   5016   5016
41    3738    3738   3738   3738   3738   3738
42    2908    2908   2908   2908   2908   2908
43    4230    4230   4230   4230   4230   4230
44    2044    2044   2044   2044   2044   2044
45    4482    4482   4482   4482   4482   4482
46    2733    2733   2733   2733   2733   2733
47    2207    2207   2207   2207   2207   2207
48    3572    3572   3572   3572   3572   3572

In [0]:
df_blog.groupby(df_blog['gender']).count()

id     age   topic    sign    date    text
gender                                                
female  336091  336091  336091  336091  336091  336091
male    345193  345193  345193  345193  345193  345193

In [0]:
df_blog_sample = df_blog.head(5000)

In [0]:
df_blog_sample.shape

(5000, 7)

In [0]:
import re, string
from nltk.corpus import stopwords

def RemoveSpaces(value):
    try:
        #string = ''.join(map(str,value))
        string = " ".join(value.split())
        string = re.sub(r'^https?:\/\/<>.*[\r\n]*', '', string, flags=re.MULTILINE)
        string = re.sub(r"[^A-Za-z]", " ", string)         
        words = string.strip().lower().split()    
        words = [w for w in words if len(w)>=1]
        #words = " ".join(words)
       # words = [w for w in words if w.lower() not in stopwords.words('english')]
        return " ".join(words)	
        #return words
    except:
        return ""

In [0]:
df_blog_sample['text_clean'] = df_blog_sample['text'].apply(RemoveSpaces)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [0]:
df_blog_sample.head()

id  ...                                         text_clean
0  2059027  ...  info has been found pages and mb of pdf files ...
1  2059027  ...  these are the team members drewes van der laag...
2  2059027  ...  in het kader van kernfusie op aarde maak je ei...
3  2059027  ...                                    testing testing
4  3581210  ...  thanks to yahoo s toolbar i can now capture th...

[5 rows x 8 columns]

In [0]:
df_blog_sample['gender'] = df_blog_sample['gender'].astype(str)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [0]:
df_blog_sample['age'] = df_blog_sample['age'].astype(str)
df_blog_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   id          5000 non-null   int64 
 1   gender      5000 non-null   object
 2   age         5000 non-null   object
 3   topic       5000 non-null   object
 4   sign        5000 non-null   object
 5   date        5000 non-null   object
 6   text        5000 non-null   object
 7   text_clean  5000 non-null   object
dtypes: int64(1), object(7)
memory usage: 312.6+ KB


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [0]:
df_blog_sample['labels'] = df_blog_sample[['gender','age','topic','sign']].agg(','.join,axis=1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [0]:
df_blog_sample.head()

id  ...                              labels
0  2059027  ...                 male,15,Student,Leo
1  2059027  ...                 male,15,Student,Leo
2  2059027  ...                 male,15,Student,Leo
3  2059027  ...                 male,15,Student,Leo
4  3581210  ...  male,33,InvestmentBanking,Aquarius

[5 rows x 9 columns]

In [0]:
df_blog_sample.drop(['id','gender','age','topic','sign','date','text'],axis=1,inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3997: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [0]:
df_blog_sample.head()

text_clean                              labels
0  info has been found pages and mb of pdf files ...                 male,15,Student,Leo
1  these are the team members drewes van der laag...                 male,15,Student,Leo
2  in het kader van kernfusie op aarde maak je ei...                 male,15,Student,Leo
3                                    testing testing                 male,15,Student,Leo
4  thanks to yahoo s toolbar i can now capture th...  male,33,InvestmentBanking,Aquarius

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
df_train, df_test, y_train, y_test = train_test_split(df_blog_sample.text_clean, df_blog_sample.labels, random_state=2)

In [0]:
# import and instantiate CountVectorizer (with the default parameters)
from sklearn.feature_extraction.text import CountVectorizer

In [0]:
cvect = CountVectorizer(stop_words='english',ngram_range=(1,2))

In [0]:
cvect.fit(df_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 2), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [0]:
len(cvect.vocabulary_)

234146

In [0]:
cvect.vocabulary_

{'don': 54032,
 'say': 175394,
 'fuck': 74978,
 'implied': 97293,
 'read': 163430,
 'urllink': 215523,
 'press': 157343,
 'release': 167134,
 'gotham': 82146,
 'comics': 35640,
 'll': 118413,
 'understand': 213983,
 'got': 81487,
 'point': 153931,
 'pure': 160656,
 'anger': 5964,
 'apparently': 7295,
 'peter': 150211,
 'parker': 146419,
 'pavitr': 147662,
 'prabhakar': 156412,
 'saw': 175169,
 'thought': 204648,
 'spoof': 189746,
 'website': 224166,
 'goddamn': 79428,
 'fairly': 65896,
 'high': 91034,
 'quality': 161081,
 'artwork': 9106,
 'spider': 189372,
 'man': 124481,
 'fucking': 75054,
 'dhoti': 49529,
 'honestly': 92892,
 'hell': 89953,
 'trying': 211935,
 'appeal': 7379,
 'farmers': 66880,
 'india': 98162,
 'better': 16370,
 'fashion': 66950,
 'sense': 179110,
 'look': 119824,
 'shoes': 181458,
 'completely': 36726,
 'lost': 120801,
 'minds': 129959,
 'transcreation': 210136,
 'crap': 41634,
 'don say': 54313,
 'say fuck': 175533,
 'fuck implied': 74996,
 'implied read': 97294,

In [0]:
X_train_ct = cvect.transform(df_train)

In [0]:
X_train_ct.shape

(3750, 234146)

In [0]:
X_train_ct[0]

<1x234146 sparse matrix of type '<class 'numpy.int64'>'
	with 101 stored elements in Compressed Sparse Row format>

In [0]:
print(X_train_ct[0])

  (0, 5964)	1
  (0, 5967)	1
  (0, 7295)	1
  (0, 7339)	1
  (0, 7379)	1
  (0, 7383)	1
  (0, 9106)	1
  (0, 9109)	1
  (0, 16370)	1
  (0, 16462)	1
  (0, 35640)	2
  (0, 35646)	1
  (0, 35651)	1
  (0, 36726)	1
  (0, 36762)	1
  (0, 41634)	1
  (0, 49529)	1
  (0, 49530)	1
  (0, 54032)	1
  (0, 54313)	1
  (0, 65896)	1
  (0, 65903)	1
  (0, 66880)	1
  (0, 66885)	1
  (0, 66950)	1
  :	:
  (0, 167146)	1
  (0, 175169)	1
  (0, 175355)	1
  (0, 175394)	1
  (0, 175533)	1
  (0, 179110)	1
  (0, 179161)	1
  (0, 181458)	1
  (0, 181462)	1
  (0, 189372)	1
  (0, 189379)	1
  (0, 189746)	1
  (0, 189747)	1
  (0, 204648)	1
  (0, 204933)	1
  (0, 210136)	1
  (0, 210137)	1
  (0, 211935)	1
  (0, 211943)	1
  (0, 213983)	1
  (0, 214025)	1
  (0, 215523)	1
  (0, 216170)	1
  (0, 224166)	1
  (0, 224186)	1


In [0]:
X_test_ct = cvect.transform(df_test)

In [0]:
X_test_ct.shape

(1250, 234146)

In [0]:
print(X_test_ct[0]) #sparse matrix

  (0, 3932)	1
  (0, 5282)	1
  (0, 37654)	1
  (0, 100470)	1
  (0, 113655)	1
  (0, 134770)	1
  (0, 141509)	1
  (0, 172892)	1
  (0, 210140)	1
  (0, 210145)	1
  (0, 215523)	1
  (0, 216369)	1


In [0]:
labelvector = CountVectorizer()
label_Ct = labelvector.fit(df_blog_sample['labels'])
dict_ = label_Ct.vocabulary_

In [0]:
dict_

{'14': 0,
 '15': 1,
 '16': 2,
 '17': 3,
 '23': 4,
 '24': 5,
 '25': 6,
 '26': 7,
 '27': 8,
 '33': 9,
 '34': 10,
 '35': 11,
 '36': 12,
 '37': 13,
 '39': 14,
 '41': 15,
 '42': 16,
 '44': 17,
 '45': 18,
 '46': 19,
 'accounting': 20,
 'aquarius': 21,
 'aries': 22,
 'arts': 23,
 'automotive': 24,
 'banking': 25,
 'businessservices': 26,
 'cancer': 27,
 'capricorn': 28,
 'communications': 29,
 'consulting': 30,
 'education': 31,
 'engineering': 32,
 'female': 33,
 'gemini': 34,
 'indunk': 35,
 'internet': 36,
 'investmentbanking': 37,
 'law': 38,
 'leo': 39,
 'libra': 40,
 'libraries': 41,
 'male': 42,
 'media': 43,
 'museums': 44,
 'non': 45,
 'pisces': 46,
 'profit': 47,
 'recreation': 48,
 'religion': 49,
 'sagittarius': 50,
 'science': 51,
 'scorpio': 52,
 'sports': 53,
 'student': 54,
 'taurus': 55,
 'technology': 56,
 'virgo': 57}

In [0]:
from sklearn.preprocessing import MultiLabelBinarizer

In [0]:
mlb = MultiLabelBinarizer()

In [0]:
y_train_MLB = mlb.fit_transform(y_train)

In [0]:
y_train_ML[0]

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1])

In [0]:
y_test_MLB = mlb.transform(y_test)

In [0]:
y_test_MLB[0]

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1])

In [0]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

In [0]:
clf = LogisticRegression(solver = 'lbfgs')
clf = OneVsRestClassifier(clf)

In [0]:
clf.fit(X_train_ct, y_train_MLB)

/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 0 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 25 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 29 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 35 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 36 is present in all training examples.
  str(classes[c]))


OneVsRestClassifier(estimator=LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='auto',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False),
                    n_jobs=None)

In [0]:
from sklearn import metrics
from sklearn.metrics import classification_report

In [145]:
metrics.accuracy_score(y_test_MLB, clf.predict(X_test_ct))

0.5056

In [0]:
y_predict = clf.predict(X_test_ct)

In [147]:
print(classification_report(y_test_MLB,y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1250
           1       0.91      0.23      0.36        44
           2       0.88      0.43      0.58       233
           3       0.71      0.33      0.45       229
           4       0.87      0.92      0.89       820
           5       0.85      0.54      0.67       292
           6       0.81      0.87      0.84       697
           7       0.00      0.00      0.00        65
           8       0.85      0.26      0.40       112
           9       0.00      0.00      0.00        24
          10       0.83      0.87      0.85       701
          11       0.88      0.30      0.45        46
          12       0.94      0.25      0.39        60
          13       0.79      0.17      0.27        66
          14       0.00      0.00      0.00        14
          15       1.00      0.30      0.47        23
          16       0.85      0.28      0.42       163
          17       0.00    

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [182]:
y_test_MLB[1249]

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0])

In [160]:
y_test

3566              male,35,Technology,Aries
4252          female,34,indUnk,Sagittarius
1918              male,35,Technology,Aries
4111          female,34,indUnk,Sagittarius
1471              male,35,Technology,Aries
                       ...                
3444              male,35,Technology,Aries
2624              male,35,Technology,Aries
1691              male,35,Technology,Aries
3706    male,39,Communications-Media,Libra
4575          female,34,indUnk,Sagittarius
Name: labels, Length: 1250, dtype: object

In [183]:
y_predict[1249]

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0])

In [186]:
#Matched labels 1-3, 5, 1249 records
print(y_test[3566])
print(y_test[4252])
print(y_test[1918])
print(y_test[1471])
print(y_test[4575])

male,35,Technology,Aries
female,34,indUnk,Sagittarius
male,35,Technology,Aries
male,35,Technology,Aries
female,34,indUnk,Sagittarius


In [187]:
#Matched predict labels 0-2, 4, 1249 records
print(y_predict[0])
print(y_predict[1])
print(y_predict[2])
print(y_predict[4])
print(y_predict[1249])

[1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 1 1 0 1 1
 1 1 0 0 1 1 0 0 0 0 1]
[1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 1 1 0 1 1 1 1
 1 0 0 0 1 1 1 1 0 0 0]
[1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 1 1 0 1 1
 1 1 0 0 1 1 0 0 0 0 1]
[1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 1 1 0 1 1
 1 1 0 0 1 1 0 0 0 0 1]
[1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 1 1 0 1 1 1 1
 1 0 0 0 1 1 1 1 0 0 0]
