# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [11]:
!pip install -U tensorflow==2.0

     |████████████████████████████████| 86.3MB 71kB/s 
     |████████████████████████████████| 450kB 48.3MB/s 
     |████████████████████████████████| 3.8MB 32.5MB/s 
     |████████████████████████████████| 81kB 9.1MB/s 
ERROR: tensorboard 2.0.2 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.11.0 which is incompatible.
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: google-auth 1.4.2
    Uninstalling google-auth-1.4.2:
      Successfully uninstalled google-auth-1.4.2
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstalle

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
from sklearn.datasets import load_iris
df_iris = load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
features = df_iris.data
labels = df_iris.target

In [176]:
print(labels)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.25, random_state=42)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
from keras.utils import np_utils

y_train=np_utils.to_categorical(y_train,3)
y_test=np_utils.to_categorical(y_test,3)


## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
from tensorflow.keras.models import Sequential

# Import `Dense` from `keras.layers`
from tensorflow.keras.layers import Dense
model = Sequential()



## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
# Add an input layer 
model.add(Dense(4, activation='sigmoid', input_shape=(4,)))
model.add(Dense(3, activation='softmax', input_shape=(3,)))

In [182]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
### Compile the model
model.compile(loss='categorical_crossentropy',
#model.compile(loss='binary_crossentropy',
              optimizer='SGD',
              metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [184]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [185]:
history = model.fit(X_train, y_train,epochs=100, batch_size=1, verbose=1)

Train on 112 samples
Epoch 1/100
112/112 [==============================] - 0s 3ms/sample - loss: 1.1255 - accuracy: 0.4464
Epoch 2/100
112/112 [==============================] - 0s 1ms/sample - loss: 1.0544 - accuracy: 0.6339
Epoch 3/100
112/112 [==============================] - 0s 1ms/sample - loss: 1.0091 - accuracy: 0.6518
Epoch 4/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.9734 - accuracy: 0.6964
Epoch 5/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.9375 - accuracy: 0.7232
Epoch 6/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.9046 - accuracy: 0.6607
Epoch 7/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.8708 - accuracy: 0.7054
Epoch 8/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.8389 - accuracy: 0.7411
Epoch 9/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.8088 - accuracy: 0.7321
Epoch 10/100
112/112 [==============================

## Question 10

### Make predictions
- Predict labels on one row

In [0]:
import numpy as np
y_pred = np.round(model.predict(X_test))

In [187]:
y_pred[0:1]

array([[0., 1., 0.]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [188]:
y_test[0:1]



array([[0., 1., 0.]], dtype=float32)

In [194]:
score = model.evaluate(X_test, y_pred,verbose=1)

print(score)

38/38 [==============================] - 0s 3ms/sample - loss: 0.1651 - accuracy: 1.0000
[0.1651005839046679, 1.0]




---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [75]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [0]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

In [42]:
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/gdrive')



Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
df_stockPrice = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/prices.csv")

In [144]:
df_stockPrice.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
date      851264 non-null object
symbol    851264 non-null object
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB


## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
df_stockPrice.drop("date", axis = 1, inplace=True)
df_stockPrice.drop("symbol", axis= 1, inplace=True)

In [146]:
df_stockPrice.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 5 columns):
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5)
memory usage: 32.5 MB


## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
df_Trim_StockPrice = df_stockPrice.head(1000)

In [148]:
df_Trim_StockPrice.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
open      1000 non-null float64
close     1000 non-null float64
low       1000 non-null float64
high      1000 non-null float64
volume    1000 non-null float64
dtypes: float64(5)
memory usage: 39.2 KB


## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
labels = df_Trim_StockPrice['volume']
features = df_Trim_StockPrice.drop("volume", axis=1)

In [0]:
labels = np.divide(labels,1000000)

In [151]:
labels

0       2.1636
1       2.3864
2       2.4895
3       2.0063
4       1.4086
        ...   
995     2.1332
996     1.9824
997    37.1528
998     6.5686
999     5.6043
Name: volume, Length: 1000, dtype: float64

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
labels = labels.astype('float32')

In [153]:
labels.dtype

dtype('float32')

In [0]:
labels = np.array(labels)

In [155]:
labels.shape

(1000,)

In [156]:
labels.dtype

dtype('float32')

In [0]:
features = features.apply(np.float32)

In [158]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
open     1000 non-null float32
close    1000 non-null float32
low      1000 non-null float32
high     1000 non-null float32
dtypes: float32(4)
memory usage: 15.8 KB


In [0]:
features = np.array(features)

In [160]:
features.shape

(1000, 4)

In [161]:
features.dtype

dtype('float32')

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
features = tf.math.l2_normalize(features)

In [163]:
features

<tf.Tensor: shape=(1000, 4), dtype=float32, numpy=
array([[0.02202894, 0.02245906, 0.02182905, 0.02253223],
       [0.02235197, 0.02141321, 0.02140607, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051192, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.0079956 , 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

In [164]:
features.shape

TensorShape([1000, 4])

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
w = tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1))

In [166]:
print(w)

tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]], shape=(4, 1), dtype=float32)


## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function
def prediction(features, w, b):
  y_pred = tf.add(tf.matmul(features,w),b)
  return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
@tf.function
def loss(y_actual, y_predicted):
  diff = y_actual - y_predicted
  sqr = tf.square(diff)
  avg = tf.reduce_mean(sqr)
  return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(X, y_actual, w, b, learning_rate = 0.01):
  with tf.GradientTape() as t:
    t.watch([w,b])
    current_prediction = prediction(X,w,b)
    current_loss = loss(y_actual, current_prediction)
  dw,db = t.gradient(current_loss, [w,b])
  w = w - learning_rate * dw
  b = b - learning_rate * db
  return w,b



## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [170]:
for i in range(100):
  w,b = train(features, labels, w, b)
  print('Current training loss on iteration', i,loss(labels,prediction(features,w,b)).numpy())

Current training loss on iteration 0 236.16759
Current training loss on iteration 1 235.09299
Current training loss on iteration 2 234.06102
Current training loss on iteration 3 233.06998
Current training loss on iteration 4 232.11781
Current training loss on iteration 5 231.20381
Current training loss on iteration 6 230.32585
Current training loss on iteration 7 229.48265
Current training loss on iteration 8 228.67297
Current training loss on iteration 9 227.89539
Current training loss on iteration 10 227.14832
Current training loss on iteration 11 226.43114
Current training loss on iteration 12 225.74234
Current training loss on iteration 13 225.0808
Current training loss on iteration 14 224.44553
Current training loss on iteration 15 223.835
Current training loss on iteration 16 223.24931
Current training loss on iteration 17 222.68655
Current training loss on iteration 18 222.14595
Current training loss on iteration 19 221.62688
Current training loss on iteration 20 221.12842
Curre

### Observe values of Weight
- Print the updated values

In [171]:
print(w.numpy())

[[0.0547828 ]
 [0.05488191]
 [0.05422735]
 [0.05533117]]


### Observe values of Bias
- Print the updated values

In [173]:
print(b.numpy())

[4.607657]
